name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Compile code
        if: matrix.os != 'windows-latest'
        run: gcc code/main.c -o main
      - name: Setup Windows build environment
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compile code (Windows)
        if: matrix.os == 'windows-latest'
        run: cl code/main.c /Fe:main ws2_32.lib
      - name: Run IPv4 test
        run: ./main ipv4
      - name: Run IPv6 test
        run: ./main ipv6
      - name: Run dual stack test
        run: ./main dual
